---
'*.mongo':
  type: mongo
  npipe_start: 'mongo --quiet'
  npipe_com: 'mongo'
  npipe_type: 'c'
  npipe_ft: 'javascript'
  npipe_append: 1
'*.mongo.ls':
  type: mongols
  npipe_com: 'lsc -cbp | mongo'
  npipe_type: 's'
  npipe_ft: 'javascript'
'*.sql':
  type: sql
  npipe_start: 'sqlite3 ~/data.db'
  npipe_com: 'sqlite3 ~/data.db'
  npipe_type: 'c'
  npipe_split: '20new'
"*.c":
  npipe_com: 'gcc -S -xc -c -o - -'
  npipe_type: 's'
  npipe_ft: 'asm'
